getAlby/bitcoin-connect

LICENSE
README.md

> The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
;)

Add license.

---

dev/vite/package.json
dev/vite/yarn.lock
package.json
react/package.json
react/yarn.lock
yarn.lock

Fixes https://github.com/getAlby/bitcoin-connect/issues/76

chore: update lit to v3

---

dev/vite/balance.html
dev/vite/index.html
src/components/bc-button.ts
src/components/bc-modal.ts
src/state/store.ts

fixes https://github.com/getAlby/bitcoin-connect/issues/69

fix: only fetch connector info if components are visible

---

src/components/bc-modal.ts
src/components/bc-router-outlet.ts
src/components/bc-start.ts
src/components/internal/bci-connecting.ts
src/components/pages/bc-lnbits.ts
src/components/pages/bc-mutiny.ts
src/components/pages/bc-nwc.ts
src/components/pages/bc-umbrel.ts
src/state/store.ts

partially fixes https://github.com/getAlby/bitcoin-connect/issues/83

fix: do not change route while connecting

---

package.json
react/package.json

Add the "repository" field to the package.json based on https://docs.npmjs.com/cli/v6/configuring-npm/package-json#repository

add "repository" field to package.json

---

src/api.ts
src/components/bc-modal.ts
src/components/twind/withTwind.ts

Fixes https://github.com/getAlby/bitcoin-connect/issues/180

fix: remove modal closing animation

---

README.md
dev/vite/index.html
package.json
react/package.json
react/src/index.ts
react/yarn.lock
src/api.ts
src/state/store.ts

Fixes https://github.com/getAlby/bitcoin-connect/issues/177

feat: add api function to get connector config

---

src/components/templates/hr.ts

Fixes https://github.com/getAlby/bitcoin-connect/issues/127

increased text spacing by 2px and increased divider opacity

---

src/components/bc-connector-list.ts
src/components/connectors/bc-lnfi-nwc-connector.ts
src/components/connectors/index.ts
src/components/icons/connectors/lnfiIcon.ts
src/components/pages/bc-lnfi.ts
src/components/routes.ts
src/connectors/index.ts

Add components->connectors->bc-lnfi-nwc-connector.ts  and suppot micro node nwc connection string

feat:add micro-node

---

dev/vite/index.html
src/components/pages/bc-lnbits.ts
src/connectors/LnbitsConnector.ts

plus a few lnbits improvements:
- remove trailing slash in URL
- remove set placeholder URL rather than default value

feat: add lnbits make invoice function

---

src/components/pages/bc-mutiny.ts

Fixes https://github.com/getAlby/bitcoin-connect/issues/231

fix: mutiny instructions

---

src/components/connectors/bc-lnfi-nwc-connector.ts
src/components/pages/bc-lnfi.ts

1. fix:mirco node connect to MicroNode Connect

fix:mirco node connect to MicroNode Connect

---

README.md
demos/html/index.html
package.json
react/package.json
react/yarn.lock
src/components/pages/bc-send-payment.ts

Fixes https://github.com/getAlby/hub/issues/480

fix: use canvas QR instead of data URL to prevent CSP error

---

src/components/bc-modal.ts
src/components/twind/withTwind.ts

This PR addresses Issue #132 by adding:
- Slide Up Animation: Modal opens with a slide-up effect in mobile screens.
- Slide Down Animation: Modal closes with a slide-down effect in mobile screens.
These enhancements improve the visual experience on mobile devices.
Changes
- Added CSS animations for transitions.
- Updated JavaScript to trigger animations on modal open/close.
Testing
- Verified responsiveness and functionality on mobile browsers.
Let me know if you'd like further adjustments! 😊

Added slide up animation on modal open in mobile

---

src/components/bc-modal.ts
src/components/flows/bc-payment.ts
src/components/pages/bc-connected.ts
src/components/routes.ts
src/state/boot.ts
src/state/store.ts

Closes https://github.com/getAlby/bitcoin-connect/issues/100

feat: add connection success screen

---

src/components/bc-modal.ts
src/components/pages/bc-lnbits.ts
src/components/pages/bc-lnfi.ts
src/components/pages/bc-mutiny.ts
src/components/pages/bc-nwc.ts

feat: improve modal and input styles in dark mode

---

dev/vite/pay-button.html
package.json
react/package.json
react/yarn.lock
src/components/pages/bc-connected.ts

Fixes https://github.com/getAlby/bitcoin-connect/issues/286

fix: only close modal after connection animation if component is still connected

---

src/components/pages/bc-alby-go.ts
src/components/pages/bc-flash-wallet.ts
src/components/pages/bc-send-payment.ts

fix: add white border around QR code on dark mode. see #292 #296

fix: add white border around QR code on dark mode.

---

README.md
react/src/index.ts
src/api.ts

Exposed connect through api

---

README.md
dev/vite/index.html
src/state/store.ts
src/types/BitcoinConnectConfig.ts

NWC auto connect via app URL

---

src/api.ts
src/state/store.ts

chore: remove circular dependency

---

demos/react/package.json
demos/react/yarn.lock
react/package.json

Fixes https://github.com/getAlby/bitcoin-connect/issues/264

Update package.json to handle react above 19

---

src/components/bc-connector-list.ts
src/components/bc-start.ts

fixes #182 
https://github.com/user-attachments/assets/46e0a6d4-b4a6-45b3-882d-a1bd365079c7

fix: focus on get-one-here button in bc-start
